[package]
name = "dodeca-debug"
version = "0.6.1"
edition = "2024"

[package.metadata]

[package.metadata."docs.rs"]
rustdoc-args = ["--html-in-header", "arborium-header.html"]

[dependencies]
backtrace.workspace = true
libc.workspace = true
