[package]
name = "integration-tests"
version = "0.6.1"
edition = "2024"
rust-version = "1.91"
publish = false

[[bin]]
name = "integration-tests"
path = "src/main.rs"

[dependencies]
facet-json.workspace = true
facet-value.workspace = true
fs-err.workspace = true
owo-colors.workspace = true
passfd.workspace = true
regex.workspace = true
tempfile.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
ureq.workspace = true
ur-taking-me-with-you.workspace = true

[dev-dependencies]
libc.workspace = true
